version: '3.8'

services:
  frontend:
    container_name: faltauno-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Backend URL - usa el nombre del contenedor del backend
      - NEXT_PUBLIC_API_URL=http://backend:8080
      # Google Maps API Key
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      # Montar código para hot-reload
      - .:/app
      # Excluir carpetas que no necesitan sincronización
      - /app/node_modules
      - /app/.next
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    external: true